### ISSUE TITLE
 Error: Could not find player config

### ISSUE THREAD

**Issue by starnger** [code-diggers-369/sangit-a-musicapp#5]
PS E:\sangit-a-musicapp-master\server> node index.js
Server Works !!! At port 5000
(node:4668) UnhandledPromiseRejectionWarning: Error: Could not find player config
    at exports.getBasicInfo (E:\sangit-a-musicapp-master\server\node_modules\ytdl-core\lib\info.js:59:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.<computed> [as getBasicInfo] (E:\sangit-a-musicapp-master\server\node_modules\ytdl-core\lib\info.js:296:18)
    at async exports.getFullInfo (E:\sangit-a-musicapp-master\server\node_modules\ytdl-core\lib\info.js:187:14)
    at async Function.exports.<computed> [as getInfo] (E:\sangit-a-musicapp-master\server\node_modules\ytdl-core\lib\info.js:296:18)
(node:4668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without 
a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI 
flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by starnger** [comment]
Please help I cant run it

**Comment by code-diggers-369** [comment]
just update ytdl-core => ^2.1.1 to ytdl-core => ^4.1.4 or latest one ok
